### ISSUE TITLE
Trash

### ISSUE THREAD

**Issue by eric48906** [Summaw/Discord-Token-Booster#1]
This is pathetic, imagine not knowing what HTTP requests are. Additionally, having to solve the captcha **ruins the whole point**. At this point, just do it yourself 😆

**Comment by Summaw** [comment]
> This is pathetic, imagine not knowing what HTTP requests are. Additionally, having to solve the captcha **ruins the whole point**. At this point, just do it yourself 😆 

Well that's your opinion. It's not that I don't know what http requests are and that I don't know how to use them. This was simply a basic project that I didn't want to continue anymore that's all. Also if someone really wanted to it's very basic to add a solver like nopecha extension to this. And with this at the time of the release (I haven't tried this in a while) you simply didn't have to solve captcha when login only when new tokens needed to join server. Anyways I'll close this now, have a good one.

**Comment by eric48906** [comment]
Yet you know all those languages (in your README)?, lmao liar

**Comment by Summaw** [comment]
> Yet you know all those languages (in your README)?, lmao liar

Well I like puppeteer is there a problem with me enjoying it?

**Comment by eric48906** [comment]
Yes there is 🤮

**Comment by Summaw** [comment]
> Yes there is 🤮 
> 
> 

Okay well your problem I guess 🤣

**Comment by eric48906** [comment]
Skill issue, imagine not knowing HTTP requests, get off github g

**Comment by Summaw** [comment]
> Skill issue, imagine not knowing HTTP requests, get off github g

Crazy how you can tell someones whole skill and knowledge by a secondary GitHub account 🤣
